---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-configmap
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is Version 1.0 </h1>
    </html>
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-app
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo-app
  replicas: 3 
  template: 
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
            - name: demo-app-index-file
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: demo-app-index-file
        configMap:
          name: demo-app-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-app
  type: LoadBalancer
